### ISSUE TITLE
License agreement popup on first run implies JPEGsnoop is not under GPL, clarification needed

### ISSUE THREAD

**Issue by Googulator** [ImpulseAdventure/JPEGsnoop#41]
The most recent release on GitHub pops up a license window on first startup, showing a freeware-but-copyrighted license agreement. On GitHub itself, JPEGsnoop is stated to be under GPLv2. This seems to be a contradiction, and should be clarified.

**Comment by ImpulseAdventure** [comment]
Thank you very much for noticing this discrepancy. As I released the source code under the terms of the GPLv2 (as shown in GitHub) I have now revised (f2840c9) the first-run dialog text accordingly.

**Comment by BrianPuccio** [comment]
Hi @ImpulseAdventure ... thanks for making this change, I was actually just about to open a ticket regarding this issue. Do you have plans to post a pre-compiled Windows binary with the license change? Thanks!

**Comment by ImpulseAdventure** [comment]
Hi @BrianPuccio -- I have now added a compiled Windows binary (titled v1.8.0a) to the [v1.8.0 release notes](https://github.com/ImpulseAdventure/JPEGsnoop/releases/tag/v1.8.0) with the license change. Hope that helps!

**Comment by BrianPuccio** [comment]
Thanks, much appreciated, sorry to be pedantic :1st_place_medal:
