### ISSUE TITLE
Real or fake

### ISSUE THREAD

**Issue by Goku-hue** [ImpulseAdventure/JPEGsnoop#59]
![Screenshot_20240727-214824_WhatsApp](https://github.com/user-attachments/assets/dce25d30-66b8-46ef-b286-6da2dd9fb264)
It's real or fake

**Comment by KuDoZ007** [comment]
That's not what this tool is for mate. This also isn't an actual issue, just a question.

**Comment by ImpulseAdventure** [comment]
Thanks @KuDoZ007 ! Closing.
